### ISSUE TITLE
ScanType enum missing "Xeno"

### ISSUE THREAD

**Issue by mgraham-dev** [Xjph/ObservatoryFramework#4]
per InsaneGolgatha on discord:
`The JSON value could not be converted to Observatory.Framework.Files.ParameterTypes.ScanType. Path: $.ScanType | LineNumber: 0 | BytePositionInLine: 74.
File: Journal.190427182712.01.log
Line: { "timestamp":"2019-04-28T01:30:59Z", "event":"Scanned", "ScanType":"Xeno" }`

**Comment by Xjph** [comment]
c28a0b9
